version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=account
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
